export const AIR_GET_CONFIG = 'AIR_GET_CONFIG';
export const AIR_SAVE_CONFIG = 'AIR_SAVE_CONFIG';
export const MINIMIZE_WINDOW = 'MINIMIZE_WINDOW';
export const MAX_RESTORE_WINDOW = 'MAX_RESTORE_WINDOW';
export const IS_MAXIMIZE_WINDOW = 'IS_MAXIMIZE_WINDOW';
export const CLOSE_WINDOW = 'CLOSE_WINDOW';
export const UPDATE_REQUEST_HEADERS = 'UPDATE_REQUEST_HEADERS';
export const GET_FILE_CONTENT = 'GET_FILE_CONTENT';
export const WEBDAV_SYNC = 'WEBDAV_SYNC';
export const AIR_OPEN_FILE = 'AIR_OPEN_FILE';
export const IMPORT_BACKUP = 'IMPORT_BACKUP';

/**
 * webview 使用
 */
export const WEBVIEW_PLAY_VIDEO = 'WEBVIEW_PLAY_VIDEO';
