name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        architecture: [x86, x64]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 16
          architecture: ${{ matrix.architecture }}

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.TOKEN }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

          args: '--config electron-builder.config.js --config.asar=false'
        env:
          VITE_HK_PRIVATE_KEY: ${{ secrets.HK_PRIVATE_KEY }}

      - name: Prepare artifact
        if: success()
        id: prepareArtifact
        run: |
          $airSetupName=ls 'dist/空气 Setup *.exe';$airSetupName=$airSetupName[0].Name.replace('.exe', '');echo "::set-output name=airSetupName::$airSetupName"

      - name: Upload air
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.prepareArtifact.outputs.airSetupName }}-${{ matrix.architecture }}
          path: './dist/*.exe'

      - name: Post to channel
        if: ${{ github.event_name != 'pull_request' && success() && github.ref == 'refs/heads/main' }}
        env:
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
        run: |
          if (-not [String]::IsNullOrEmpty("${{ secrets.TELEGRAM_TOKEN }}")) {
            $airSetup="./dist/{{ steps.prepareArtifact.outputs.airSetupName }}.exe"
            echo $airSetup
            curl -v "https://api.telegram.org/bot$env:TELEGRAM_TOKEN/sendMediaGroup?chat_id=$env:TELEGRAM_TO&media=%5B%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2FairSetup%22%7D%5D%22" -F airSetup="@$airSetup"
          }
